title: FM
author: Farzad Maleki
description: "I study patternsâ€”in markets, minds, and meaning."
# IMPORTANT: Replace "your-username" with your actual GitHub username.
url: "https://farzadona.com"
baseurl: ""
email: farzadona@gmail.com
linkedin_url: "https://www.linkedin.com/in/farzadona/"

# Build settings
theme: minima # A good default theme, can be removed if you want 100% custom styling.
future: true


# Header pages

